CFLAGS=-Wall -pedantic -std=c11 -I../../utils -L../../lib
LIBS=-lutils

all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10

test1: test1.c
			 gcc $(CFLAGS) test1.c $(LIBS) -o $@

test2: test2.c
			 gcc $(CFLAGS) test2.c $(LIBS) -o $@

test3: test3.c
			 gcc $(CFLAGS) test3.c $(LIBS) -o $@

test4: test4.c
			 gcc $(CFLAGS) test4.c $(LIBS) -o $@

test5: test5.c
			 gcc $(CFLAGS) test5.c $(LIBS) -o $@

test6: test6.c
			 gcc $(CFLAGS) test6.c $(LIBS) -o $@

test7: test7.c
			 gcc $(CFLAGS) test7.c $(LIBS) -o $@

test8: test8.c
			 gcc $(CFLAGS) test8.c $(LIBS) -o $@

test9: test9.c
			 gcc $(CFLAGS) test9.c $(LIBS) -o $@

test10: test10.c
			  gcc $(CFLAGS) test10.c $(LIBS) -o $@

clean:
					rm -f *.o test1 test2 test3 test4 test5 test6 test7 test8 test9 test10
